url: "https://scsok.io"
title: "Single Cell & Spatial Omics Korea"
github_url: https://github.com/singlecell-spatialomics-korea
zulip_url: https://zulip.scsok.io

future: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

navigation:
  - label: People
    url: /people/
  - label: Events
    url: /events/
  - label: Research
    url: /research/
  - label: Publications
    url: /publications/
  - label: Jobs
    url: /jobs/

plugins:
  - jekyll-postcss

collections:
  researches:
    output: true
    permalink: /researches/:slug

# slug 생성 규칙 설정
slug:
  mode: pretty
  cased: lowercase

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3