url: "https://scsok.io"
title: "Single Cell & Spatial Omics Korea"
github_url: https://github.com/singlecell-spatialomics-korea
zulip_url: https://zulip.scsok.io

future: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

navigation:
  - label: People
    url: /people/
  - label: Events
    url: /events/
  - label: Research
    url: /research/
  - label: Publications
    url: /publications/
  - label: Jobs
    url: /jobs/

collections:
  researches:
    output: true
    permalink: /researches/:slug