url: "https://scsok.io"
title: "Single Cell & Spatial Omics Korea"
github_url: https://github.com/singlecell-spatialomics-korea
zulip_url: https://zulip.scsok.io

future: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

navigation:
  - label: Research Groups
    url: /research-groups/
  - label: Researchers
    url: /researchers/
  - label: Events
    url: /events/
  - label: Methods
    url: /methods/
  - label: Publications
    url: /publications/
  - label: Jobs
    url: /jobs/