name: scsok-home
channels:
- conda-forge
- pkgs/main
dependencies:
- _libgcc_mutex
- _openmp_mutex
- appdirs
- attrs
- brotli-python
- ca-certificates
- cachecontrol
- cachy
- certifi
- charset-normalizer
- cleo
- click
- click-default-group
- conda-lock
- ensureconda
- filelock
- gdbm
- gmp
- html5lib
- idna
- importlib-metadata
- jinja2
- jsonschema
- ld_impl_linux-64
- libffi
- libgcc-ng
- libgomp
- libstdcxx-ng
- lockfile
- markupsafe
- msgpack-python
- ncurses
- openssl
- packaging
- pastel
- pip
- pkginfo
- poetry
- pydantic
- pylev
- pyparsing
- pyrsistent
- pysocks
- python
- python_abi
- pyyaml
- readline
- requests
- requests-toolbelt
- ruamel.yaml
- ruamel.yaml.clib
- ruby
- setuptools
- shellingham
- six
- sqlite
- tk
- tomli
- tomlkit
- toolz
- typing-extensions
- typing_extensions
- urllib3
- webencodings
- wheel
- xz
- yaml
- zipp
- zlib

